### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Capevace** [bildschirm/bildschirm#5]
In order for bildschirm to be useable for other people, it needs strong documentation.

**Tasks:**
- [ ] Landing page 
  - [ ] Add "real-time state sync" graphic
- [ ] Get started
- [ ] Guides
  - [ ] Writing a plugin
  - [ ] Mission Control internals
  - [ ] Creating example API consument 
- [ ] API Reference
  - [ ] Proper code comments
